blank_issues_enabled: false
contact_links:
  - name: AXYRA Community Support
    url: https://github.com/axyra/axyra-sistema-gestion/discussions
    about: Ask questions and get help from the community
  - name: AXYRA Documentation
    url: https://axyra.vercel.app/docs
    about: Check our documentation for answers
  - name: AXYRA Security
    url: https://github.com/axyra/axyra-sistema-gestion/security/advisories/new
    about: Report a security vulnerability
